spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spirometry_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Ensures Hibernate updates schema automatically
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      schema-locations: classpath:Database/*.sql  # Reads all SQL files in the Database folder

  security:
    jwt:
      secret-key: "s8#Gv2!kLz@rNp$QyW1^dTx3&VoUbKmC"  # Secure this in production
      expiration: 3600000  # 1 hour in milliseconds
